modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = "Hardware-tailored execution engine for AVX2 and RDNA 2, providing ultra-low tick latency for Create and Sable."

[[mixins]]
config = "vortec.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "sable"
type = "optional"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
type = "optional"
ordering = "AFTER"
side = "BOTH"
